# Generated by Django 5.1.7 on 2025-03-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={"ordering": ["-joined"], "verbose_name_plural": "People"},
        ),
        migrations.RenameField(
            model_name="person",
            old_name="created",
            new_name="joined",
        ),
        migrations.AddField(
            model_name="person",
            name="bank_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="account_number",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
